export const competitionCardDetails = [
	{
		id: "1",
		title: "Mega Sunday",
		description: "weekend flagship competition with the biggest prizes",
		prizePool: "7000",
		participants: 102,
		maxParticipants: 150,
		entryFee: "50",
		timeLeft: "3h 44m",
		status: "Live",
		featured: true,
	},
	{
		id: "2",
		title: "Garba Vibe",
		description: "weekend flagship competition with the biggest prizes",
		prizePool: "9000",
		entryFee: "120",
		participants: 95,
		maxParticipants: 130,
		timeLeft: "4h 34m",
		status: "upcoming",
		featured: true,
	},
	{
		id: "1",
		title: "Garba Vibe",
		description: "weekend flagship competition with the biggest prizes",
		prizePool: "11,000",
		entryFee: "150",
		participants: 72,
		maxParticipants: 100,
		timeLeft: "3h 22m",
		status: "live",
		featured: true,
	},
	{
		id: "1",
		title: "Mega Sunday Madness",
		description: "weekend flagship competition with the biggest prizes",
		prizePool: "13,000",
		entryFee: "170",
		participants: 65,
		maxParticipants: 90,
		timeLeft: "3h 07m",
		status: "upcoming",
		featured: true,
	},
];
